project_name: hello-world-cli

before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
builds:
  -
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/ondrejsika/hello-world-cli/version.Version=v{{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"
      - goos: linux
        goarch: arm
        goarm: 6
    binary: hello-world-cli

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
  -
    name: hello-world-cli
    tap:
      owner: ondrejsikademo
      name: homebrew-tap
    skip_upload: auto
    homepage: https://github.com/ondrejsika/hello-world-cli
    url_template: "https://github.com/ondrejsika/hello-world-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    caveats: "How to use this binary: https://github.com/ondrejsika/hello-world-cli"
    description: "Hello World CLI"
    install: |
      bin.install "hello-world-cli"
    test: |
      system "#{bin}/hello-world-cli"
